### ISSUE TITLE
Crash when no wine path is found

### ISSUE THREAD

**Issue by otreblan** [Dummerle/Rare#1]
```
[Rare] INFO: Try if you are logged in
[Rare] INFO: You ar not logged in. Open Login Window
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/Rare/Main.py", line 24, in main
    if core.login():
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 154, in login
    raise ValueError('No saved credentials')
ValueError: No saved credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rare", line 33, in <module>
    sys.exit(load_entry_point('rare==0.0.0', 'console_scripts', 'rare')())
  File "/usr/lib/python3.9/site-packages/Rare/Main.py", line 33, in main
    login_window = LoginWindow(core)
  File "/usr/lib/python3.9/site-packages/Rare/Login.py", line 116, in __init__
    self.import_widget = ImportWidget(self.core)
  File "/usr/lib/python3.9/site-packages/Rare/Login.py", line 39, in __init__
    self.set_appdata_path()
  File "/usr/lib/python3.9/site-packages/Rare/Login.py", line 67, in set_appdata_path
    self.core.egl.appdata_path = wine_paths[0]
IndexError: list index out of range
Release of profile requested but WebEnginePage still not deleted. Expect troubles !
```

`mkdir -p ~/.wine/drive_c/users` fixes it.

**Comment by Dummerle** [comment]
Thank you for reporting this error! The import function isn't finished yet. and my solution is not so pretty as well
