### ISSUE TITLE
Rare crashing on Arch linux

### ISSUE THREAD

**Issue by Aagame3** [Dummerle/Rare#101]
Rare started crashing seemingly randomly today with the error message: 
`Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rare/app.py", line 121, in start_app
    self.mainwindow = MainWindow(self.core, self.args)
  File "/usr/lib/python3.9/site-packages/rare/components/main_window.py", line 32, in __init__
    self.tab_widget = TabWidget(core, self, args.offline)
  File "/usr/lib/python3.9/site-packages/rare/components/tab_widget.py", line 31, in __init__
    self.games_tab = GameTab(core, self, offline)
  File "/usr/lib/python3.9/site-packages/rare/components/tabs/games/__init__.py", line 17, in __init__
    self.default_widget = Games(core, self, offline)
  File "/usr/lib/python3.9/site-packages/rare/components/tabs/games/__init__.py", line 63, in __init__
    self.game_list = GameList(core, self, offline)
  File "/usr/lib/python3.9/site-packages/rare/components/tabs/games/game_list.py", line 37, in __init__
    self.installing_widget = InstallingGameWidget(self.core.get_game("CrabEA"))
  File "/usr/lib/python3.9/site-packages/rare/components/tabs/games/game_widgets/installing_game_widget.py", line 16, in __init__
    self.pixmap = get_pixmap(game.app_name)
AttributeError: 'NoneType' object has no attribute 'app_name'
zsh: abort (core dumped)  rare
`
Any help appreciated

**Comment by Dummerle** [comment]
I will fix it
