### ISSUE TITLE
[BUG] The latest version does not open 

### ISSUE THREAD

**Issue by inkubux** [Dummerle/Rare#102]
**Describe the bug**
The latest version does not open 

**To Reproduce**
1. Install with pip or appimage
2. Open the app
3. See error

**Expected behavior**
The app opens

**Desktop (please complete the following information):**
 - OS: Fedora 34 (Gnome)
 - Rare Version 1.6 / 1.6.1
- Installation [pip/msi/AppImage]   (both)
- Python version (3.9.6)

**Additional context**

**Error message**
Error in the console 
``Traceback (most recent call last):
  File "/home/francis/.local/lib/python3.9/site-packages/rare/app.py", line 121, in start_app
    self.mainwindow = MainWindow(self.core, self.args)
  File "/home/francis/.local/lib/python3.9/site-packages/rare/components/main_window.py", line 32, in __init__
    self.tab_widget = TabWidget(core, self, args.offline)
  File "/home/francis/.local/lib/python3.9/site-packages/rare/components/tab_widget.py", line 31, in __init__
    self.games_tab = GameTab(core, self, offline)
  File "/home/francis/.local/lib/python3.9/site-packages/rare/components/tabs/games/__init__.py", line 17, in __init__
    self.default_widget = Games(core, self, offline)
  File "/home/francis/.local/lib/python3.9/site-packages/rare/components/tabs/games/__init__.py", line 63, in __init__
    self.game_list = GameList(core, self, offline)
  File "/home/francis/.local/lib/python3.9/site-packages/rare/components/tabs/games/game_list.py", line 37, in __init__
    self.installing_widget = InstallingGameWidget(self.core.get_game("CrabEA"))
  File "/home/francis/.local/lib/python3.9/site-packages/rare/components/tabs/games/game_widgets/installing_game_widget.py", line 16, in __init__
    self.pixmap = get_pixmap(game.app_name)
AttributeError: 'NoneType' object has no attribute 'app_name'``

Error in logs
`[Utils] INFO: Found locale in system config: en
[Core] INFO: Trying to re-use existing login session...
[Login] INFO: You are logged in
`

**Comment by Dummerle** [comment]
There is a newer version: 1.6.2. the hotfix fixes the error
