### ISSUE TITLE
Cant start rare on windows

### ISSUE THREAD

**Issue by Rajalolxd** [Dummerle/Rare#13]
Traceback (most recent call last):
  File "Main.py", line 63, in <module>
  File "Main.py", line 26, in main
  File "Rare\utils\RareUtils.py", line 86, in get_lang
  File "configparser.py", line 960, in __getitem__
KeyError: 'Legendary'
[4544] Failed to execute script Main

**Comment by ChemicalXandco** [comment]
Are you using the latest git version? This should have been fixed in 59bc4c0dd6fbf8d5dba60b4622aa6c36ca68e150.

**Comment by Dummerle** [comment]
I think the latest release is not up to date. I will fix it when I have time for that

**Comment by Dummerle** [comment]
I fixed the error
