### ISSUE TITLE
[BUG] No language directory

### ISSUE THREAD

**Issue by ZhaoZuohong** [Dummerle/Rare#140]
**Describe the bug**

See the screenshot below.

**To Reproduce**

1. run `pip install Rare --user` to install rare
2. login with browser
3. after login, rare starts downloading image and launch

**Expected behavior**

Rare launch normally

**Screenshots**

![image](https://user-images.githubusercontent.com/34163622/146527329-fcff2ddb-a801-4659-85bd-c2bfd365eb01.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Version 1.8.0
- Installation pip
- Python version distro shipped 3.8.10

**Additional context**

Tried in a newly installed fresh Linux Mint, the error still exists. Also tried on Ubuntu 20.04 LTS, the error is still there.

**Error message**
You can find error message in ~/.cache/rare/logs/

```
[Core] INFO: Trying to re-use existing login session...
[Login] INFO: You are logged in
[Login] INFO: App starting
[Rare] CRITICAL: Traceback (most recent call last):
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/app.py", line 146, in start_app
    self.mainwindow = MainWindow()
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/components/main_window.py", line 27, in __init__
    self.tab_widget = TabWidget(self)
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/components/tabs/__init__.py", line 37, in __init__
    self.settings = SettingsTab(self)
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/components/tabs/settings/__init__.py", line 14, in __init__
    self.rare_settings = RareSettings()
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/components/tabs/settings/rare.py", line 47, in __init__
    if language in get_translations():
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/utils/utils.py", line 190, in get_translations
    for i in os.listdir(os.path.join(resources_path, "languages")):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/resources/languages'

[Core] INFO: Trying to re-use existing login session...
[Login] INFO: You are logged in
[Login] INFO: App starting
[Rare] CRITICAL: Traceback (most recent call last):
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/app.py", line 146, in start_app
    self.mainwindow = MainWindow()
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/components/main_window.py", line 27, in __init__
    self.tab_widget = TabWidget(self)
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/components/tabs/__init__.py", line 37, in __init__
    self.settings = SettingsTab(self)
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/components/tabs/settings/__init__.py", line 14, in __init__
    self.rare_settings = RareSettings()
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/components/tabs/settings/rare.py", line 47, in __init__
    if language in get_translations():
  File "/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/utils/utils.py", line 190, in get_translations
    for i in os.listdir(os.path.join(resources_path, "languages")):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhao/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/resources/languages'
```

**Comment by MultisampledNight** [comment]
I have no idea why this happens since `MANIFEST.in` *should* include `rare/resources/languages`:

https://github.com/Dummerle/Rare/blob/bab0659e12fc22a010fd28f27293ef99f48ab741/MANIFEST.in#L3

but I hit the same, and thought it was an error with my local configuration (which it doesn't seem to be). You can work around it with (in your case)

```console
mkdir $HOME/.local/pipx/venvs/rare/lib/python3.8/site-packages/rare/resources/languages
```

for now, until someone who knows more about this fixes it.

**Comment by MultisampledNight** [comment]
Oh, figured out why. Dummerle removed `include_package_data = True` in `setup.py`, probably by accident, see https://github.com/Dummerle/Rare/commit/c425775f28b623aa94e9ac1a2669dab7daa9b213#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L32

**Comment by ZhaoZuohong** [comment]
OK, it works now. I'll close this issue.
