### ISSUE TITLE
[BUG] FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\azumu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\rare\\resources\\languages'

### ISSUE THREAD

**Issue by azumukupoe** [Dummerle/Rare#142]
**Describe the bug**

**To Reproduce**
1. Lauch Rare from Powershell
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31339007/146644442-bee530f7-05c7-4921-b38d-6e0a823d1544.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2 19044.1415
- Installation: pip
- Python version: 3.10.1

**Additional context**

**Error message**
```
Traceback (most recent call last):
  File "C:\Users\azumu\AppData\Local\Programs\Python\Python310\lib\site-packages\rare\app.py", line 146, in start_app
    self.mainwindow = MainWindow()
  File "C:\Users\azumu\AppData\Local\Programs\Python\Python310\lib\site-packages\rare\components\main_window.py", line 27, in __init__
    self.tab_widget = TabWidget(self)
  File "C:\Users\azumu\AppData\Local\Programs\Python\Python310\lib\site-packages\rare\components\tabs\__init__.py", line 37, in __init__
    self.settings = SettingsTab(self)
  File "C:\Users\azumu\AppData\Local\Programs\Python\Python310\lib\site-packages\rare\components\tabs\settings\__init__.py", line 14, in __init__
    self.rare_settings = RareSettings()
  File "C:\Users\azumu\AppData\Local\Programs\Python\Python310\lib\site-packages\rare\components\tabs\settings\rare.py", line 47, in __init__
    if language in get_translations():
  File "C:\Users\azumu\AppData\Local\Programs\Python\Python310\lib\site-packages\rare\utils\utils.py", line 190, in get_translations
    for i in os.listdir(os.path.join(resources_path, "languages")):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\azumu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\rare\\resources\\languages'
```

**Comment by MultisampledNight** [comment]
See #140, fixed in 16ffdb4, just not in a release yet. Consider installing the repository directly through `pip install --upgrade https://github.com/Dummerle/Rare/archive/refs/heads/main.zip`, use a previous release, or wait until Dummerle issues a hotfix release.

**Comment by azumukupoe** [comment]
actually, I used msi to install and didn't get the error when launching so it's alright
I'm sorry I didn't bother searching through closed issues

**Comment by MultisampledNight** [comment]
Don't worry about it, everyone has done that by accident at least once.

**Comment by Dummerle** [comment]
The bug is fixed in the latest release
