### ISSUE TITLE
[BUG] Unable to launch on Arch Linux

### ISSUE THREAD

**Issue by Gelmo** [Dummerle/Rare#144]
**Describe the bug**
A fresh install of your AUR package is producing an error for me at launch.

**To Reproduce**
- Open Rare

**Desktop (please complete the following information):**
- OS: Arch Linux
- Version: 1.8.1-1
- Installation: AUR
- Python version: 3.10.1

**Additional context**
I did not have Rare or Legendary installed previously. I assume this is related to commit 620fbe8e97ed3b6ed4c4dadc97e75e3b40f8ebd0

**Error message**
```
[Core] INFO: Trying to re-use existing login session...
[Login] INFO: You are logged in
[Login] INFO: App starting
[GamesTab] INFO: aa has a corrupt image.
[Rare] CRITICAL: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/rare/app.py", line 146, in start_app
    self.mainwindow = MainWindow()
  File "/usr/lib/python3.10/site-packages/rare/components/main_window.py", line 27, in __init__
    self.tab_widget = TabWidget(self)
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/__init__.py", line 26, in __init__
    self.games_tab = GamesTab()
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/__init__.py", line 82, in __init__
    self.setup_game_list()
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/__init__.py", line 162, in setup_game_list
    icon_widget, list_widget = self.add_installed_widget(game.app_name)
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/__init__.py", line 186, in add_installed_widget
    icon_widget = InstalledIconWidget(app_name, pixmap, self.game_utils)
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/game_widgets/installed_icon_widget.py", line 18, in __init__
    super(InstalledIconWidget, self).__init__(app_name, pixmap, game_utils)
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/game_widgets/base_installed_widget.py", line 60, in __init__
    remote_version = self.core.get_asset(self.game.app_name, platform=self.igame.platform,
AttributeError: 'NoneType' object has no attribute 'platform'
```

**Comment by Dummerle** [comment]
I pushed a fix. I hope it fixes it

**Comment by Dummerle** [comment]
1.8.2 should fix the error

**Comment by Gelmo** [comment]
It did fix that error, only to reveal the next one:
```
[Rare] CRITICAL: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/rare/app.py", line 146, in start_app
    self.mainwindow = MainWindow()
  File "/usr/lib/python3.10/site-packages/rare/components/main_window.py", line 27, in __init__
    self.tab_widget = TabWidget(self)
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/__init__.py", line 26, in __init__
    self.games_tab = GamesTab()
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/__init__.py", line 82, in __init__
    self.setup_game_list()
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/__init__.py", line 164, in setup_game_list
    icon_widget, list_widget = self.add_installed_widget(game.app_name)
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/__init__.py", line 188, in add_installed_widget
    icon_widget = InstalledIconWidget(app_name, pixmap, self.game_utils)
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/games/game_widgets/installed_icon_widget.py", line 64, in __init__
    if not self.is_origin and self.igame.needs_verification:
AttributeError: 'NoneType' object has no attribute 'needs_verification'
```

Thank you for the quick response!

**Comment by Dummerle** [comment]
I pushed a fix

**Comment by Gelmo** [comment]
Cheers! I'll test and confirm once there's a new release

**Comment by Gelmo** [comment]
@Dummerle Please update the AUR package when you have an opportunity to do so, and then I will test and confirm.

**Comment by Gelmo** [comment]
Just tested, and the issue has been resolved. Thank you very much!
