### ISSUE TITLE
[BUG] "NoneType has no attribute 'app_title'"

### ISSUE THREAD

**Issue by V3ntus** [Dummerle/Rare#151]
**Describe the bug**
```py
Traceback (most recent call last):
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\app.py", line 146, in start_app
    self.mainwindow = MainWindow()
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\components\main_window.py", line 27, in __init__
    self.tab_widget = TabWidget(self)
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\components\tabs\__init__.py", line 26, in __init__
    self.games_tab = GamesTab()
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\components\tabs\games\__init__.py", line 64, in __init__
    self.import_sync_tabs = ImportSyncTabs(self)
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\components\tabs\games\import_sync\__init__.py", line 21, in __init__
    EGLSyncGroup(self),
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\components\tabs\games\import_sync\egl_sync_group.py", line 64, in __init__
    self.update_lists()
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\components\tabs\games\import_sync\egl_sync_group.py", line 142, in update_lists
    self.import_list.populate(have_path)
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\components\tabs\games\import_sync\egl_sync_group.py", line 226, in populate
    self.list.addItem(EGLSyncListItem(item, self.export, self.list))
  File "C:\Users\Ventus\AppData\Local\Programs\Python\Python38\lib\site-packages\rare\components\tabs\games\import_sync\egl_sync_group.py", line 159, in __init__
    self.setText(shared.core.get_game(game.app_name).app_title)
AttributeError: 'NoneType' object has no attribute 'app_title'
```

**To Reproduce**
This is a fresh install on first launch. I logged in via browser

**Expected behavior**
To launch

**Desktop (please complete the following information):**
 - OS: Windows 10 - 10.0.19042 Build 19042
 - Version 1.8.2
- Installation pip
- Python 3.8.1

**Additional context**

**Error message**
You can find error message in ~/.cache/rare/logs/

**Comment by V3ntus** [comment]
Output from Legendary:
```
C:\Users\Ventus\Downloads>.\legendary.exe list-games
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)

Available games:
 * Among Us (App name: 963137e4c29d4c79a81323b8fab03a40 | Version: 2021.12.15.0)
 * ARK: Survival Evolved (App name: aafc587fbf654758802c8e41e4fb3255 | Version: 341.36.1.win)
 * Borderlands 2 (App name: Dodo | Version: 2.0.1 BN264 CL2464059)
 * Borderlands: The Pre-Sequel (App name: Turkey | Version: 2.0.1 BN133 CL2464059)
 * Core (App name: a99769d95d8f400baad1f67ab5dfe508 | Version: 1.0.226-prod-s-epic-3133)
 * Dead by Daylight (App name: Brill | Version: 5.4.2.3)
 * Fortnite (App name: Fortnite | Version: ++Fortnite+Release-19.01-CL-18489740-Windows)
 * Frostpunk (App name: b2e00fc16632475782a7730d1bd7cb60 | Version: 0.0.10)
 * Grand Theft Auto V (App name: 9d2d0eb64d5c44529cece33fe2a46482 | Version: 1.0.2545.0.1)
 * Hue (App name: Herring | Version: 1.0)
 * Inside (App name: Marigold | Version: 1.0.0)
 * Jurassic World Evolution (App name: 373a4372c20540aca7fdd880d27fa49a | Version: 1.12.7.54973)
 * KID A MNESIA EXHIBITION (App name: 33411619626243f1859d0b7fb5cc5405 | Version: 0.0333.012725)
 * Lifeless Planet: Premier Edition (App name: 860a4feefe2a4f48905ae86c61d5db64 | Version: 1.0.0)
 * NBA 2K21 (App name: 639977eecfd2497c941b71af949b5067 | Version: 1.12.253557)
 * Overcooked (App name: Sage | Version: 1.0)
 * Pathway (App name: 8fceb562623c430db9bb6abf0549c43e | Version: 1.3.3a_windows64)
 * Prison Architect (App name: 668ffa8fce0847ef9f1c005995cee6df | Version: 1.7.3.1.12.13.169)
 * Rocket League® (App name: Sugar | Version: BC2_Update36+355454)
 * Sid Meier's Civilization VI (App name: Kinglet | Version: 1.0.12.564030i_rtm)
  + Civilization VI : Aztec DLC (App name: KingletAztec | Version: 1.0.12.564030i_rtm)
 * Tacoma (App name: Flagfin | Version: 1.0)
 * Tharsis (App name: 266d978cc221471787b597695cbb9a75 | Version: 1.03)
 * The Alto Collection (App name: Hornbill | Version: 1.0.5)
 * The Escapists 2 (App name: Fowl | Version: 0.24)
 * The Lion's Song (App name: ee41ac4954314d18b18b8e7789c4e4eb | Version: tls_windows_master_standalone_691)
 * Torchlight II (App name: 8e425d507bd6473dbb927f0fea8ef4f6 | Version: 1.25.9.5)
 * while True: learn() (App name: 4f272a49a39742b795d63e1f483a7c7d | Version: 1.4.98.5144.39.win64)

Total: 27
```

**Comment by Dummerle** [comment]
Are games installed, which you don't own. 
I will push a fix

**Comment by V3ntus** [comment]
> Are games installed, which you don't own? 
> Despite,  I will push a fix

I'm not sure what would register as "not owned". Games not installed from Epic? I have Steam and GOG titles.

**Comment by Dummerle** [comment]
I hope it is fixed. I will publish a new release

**Comment by V3ntus** [comment]
Thank you!
