### ISSUE TITLE
[BUG] Running games with proton fails with code 1

### ISSUE THREAD

**Issue by neuromancer** [Dummerle/Rare#186]
**Describe the bug**
Using proton from rare seems to always fail. I tested it in ArchLinux (fully updated today), including steam runtime libraries. Steam and proton are working fine (even in "native" mode) so that shouldn't be an issue here. Wine is also working fine, even with rare.

**To Reproduce**
1. Start any game using any version of proton installed.
2. Game will not start and fail with code 1.

**Expected behavior**
Proton should run correctly.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Version: Rolling Release
- Installation: pip
- Python version: 3.10.2

**Error message**
```
[GameUtils] INFO: Launching Automachef
[Core] INFO: Getting authentication token...
[GameUtils] INFO: Automachef launched
[GameUtils] INFO: Game exited with exit code: 1
```

**Comment by MultisampledNight** [comment]
Would you mind sending the lines below the section `[Automachef]` in `~/.config/legendary/config.ini`? Also, does the `proton` path which should be listed as first element exist at all?

**Comment by Dummerle** [comment]
You can enable game debug console in rare settings. It should show more detailed information

**Comment by neuromancer** [comment]
@Dummerle: enabling debug console shows this:

```
Proton: Upgrading prefix from None to 7.0-100 (/home/g/.proton/)
Traceback (most recent call last):
  File "/home/g/.steam/steam/steamapps/common/Proton - Experimental/proton", line 1402, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/g/.steam/steam/steamapps/common/Proton - Experimental/proton", line 1207, in init_session
    g_compatdata.setup_prefix()
  File "/home/g/.steam/steam/steamapps/common/Proton - Experimental/proton", line 744, in setup_prefix
    steamdir = os.environ["STEAM_COMPAT_CLIENT_INSTALL_PATH"]
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'

Game exited with code: 1
```

@MultisampledNight. The complete file is here:

```
[Legendary]
; Disables the automatic update check
disable_update_check = false
; Disables the notice about an available update on exit
disable_update_notice = true
install_dir = /home/g/Juegos/Epic
locale = es-AR

[dd75b5c168d546cc869582c0389f0a1d]
offline = false
wine_prefix = /home/g/.wine.prefixes/Train Sim 2

[dd75b5c168d546cc869582c0389f0a1d.env]
WINEPREFIX = /home/g/.wine.prefixes/Train Sim 2

[272d51db75be476f9ad60c0e7fc24470.env]
WINEPREFIX = /home/g/.wine.prefixes/Stubbs

[272d51db75be476f9ad60c0e7fc24470]
wine_prefix = /home/g/.wine.prefixes/Stubbs

[Bulbul]
wrapper = "/home/g/.steam/steam/steamapps/common/Proton 7.0/proton" run
no_wine = true

[Bulbul.env]
STEAM_COMPAT_DATA_PATH = /home/g/.proton

[Curry]
wrapper = "/home/g/.steam/steam/steamapps/common/Proton 6.3/proton" run
no_wine = true

[Curry.env]
STEAM_COMPAT_DATA_PATH = /home/g/.proton

[860a4feefe2a4f48905ae86c61d5db64]
wrapper = "/home/g/.steam/steam/steamapps/common/Proton 6.3/proton" run
no_wine = true

[860a4feefe2a4f48905ae86c61d5db64.env]
STEAM_COMPAT_DATA_PATH = /home/g/.proton

[069a60f6b0514a5fbe81b38957c1ddfd]
wrapper = "/home/g/.steam/steam/steamapps/common/Proton - Experimental/proton" run
no_wine = true

[069a60f6b0514a5fbe81b38957c1ddfd.env]
STEAM_COMPAT_DATA_PATH = /home/g/.proton
```

**Comment by neuromancer** [comment]
A workaround that seems to work: 

```
$ STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/steam" rare
```

**Comment by Dummerle** [comment]
I thought I added $STEAM_COMPAT_CLIENT_INSTALL_PATH in proton environment. I will push a fix later
