### ISSUE TITLE
Rare won't launch

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#22]
I installed the rare 0.9.7-1 from AUR on Archlinux, and after install I get this when launched in the terminal..
I'm I missing something for it to work??

$ rare
Traceback (most recent call last):
  File "/usr/bin/rare", line 33, in <module>
    sys.exit(load_entry_point('Rare==0.9.7', 'console_scripts', 'rare')())
  File "/usr/bin/rare", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'Rare.__main__' has no attribute 'main'

**Comment by Dummerle** [comment]
Yes, I noticed it. A new release is created
