### ISSUE TITLE
[BUG] Fails to launch on Legendary 0.20.30

### ISSUE THREAD

**Issue by SuperSamus** [Dummerle/Rare#257]
**Describe the bug**
Launching Rare when using Legendary 0.20.30 returns (sorry for the bloated file paths):

```
Traceback (most recent call last):
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/bin/.rare-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/__main__.py", line 104, in main
    from rare.app import start
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/app.py", line 15, in <module>
    from rare.components.dialogs.launch_dialog import LaunchDialog
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/components/dialogs/launch_dialog.py", line 10, in <module>
    from rare.components.dialogs.login import LoginDialog
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/components/dialogs/login/__init__.py", line 13, in <module>
    from .import_login import ImportLogin
  File "/nix/store/pwkh2p8pd4qbizrbqjw87s4r1jc8r7ma-rare-1.9.2/lib/python3.10/site-packages/rare/components/dialogs/login/import_login.py", line 8, in <module>
    from legendary.utils.wine_helpers import read_registry, get_shell_folders
ModuleNotFoundError: No module named 'legendary.utils.wine_helpers'
``` 

It seems to be caused by this commit: https://github.com/derrod/legendary/commit/85f6bd3220f8eddd3d2ae3ef0c434b8c4968a0a0.

**Desktop (please complete the following information):**
 - OS: Linux NixOS 21.11
 - Version: 1.9.2
- Installation: distro package
- Python version: 3.10

**Comment by loathingKernel** [comment]
Has been fixed in https://github.com/Dummerle/Rare/commit/923aa1b90de133b235fc7069d8375edf2ff1300a and https://github.com/Dummerle/Rare/commit/e208daf545c06b212a774f7fafbf5f76baf374e5

**Comment by SuperSamus** [comment]
Oh, I didn't check hard enough.
I'll close this when a new version is released.
