### ISSUE TITLE
[BUG] [pacman] Crash on start

### ISSUE THREAD

**Issue by babaruh** [Dummerle/Rare#307]
At the first launch rare crashes like

`
$ rare     
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rare", line 33, in <module>
    sys.exit(load_entry_point('Rare==1.9.5', 'console_scripts', 'rare')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/rare", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for Rare
`

- Operating system: ArcoLinux
- Version 1.10.3-1
- Installation method pacman
- Python version 3.11, pip 23.2.1

no logs in `~/.cache/Rare/Rare/logs`

**Comment by loathingKernel** [comment]
This looks to me like a problem with your local python installation. That version of Rare (`1.9.5` from the logs) is also quite old. So far from this information I think this problem is not necessarily related to Rare. How did you install Rare, is there any chance you have Rare for an older `python` installation, for example 3.10? In that case you need to rebuild the package.

**Comment by babaruh** [comment]
I install it by pacman(archlinux package manager) and all up to date(as pacman says)

**Comment by loathingKernel** [comment]
There isn't an Archlinux package for Rare in the Archlinux repositories, so if you installed it through `pacman` , the repository you are pulling it from needs to update it (I see you are using ArcoLinux, in which case I don't know the repos you are using).  There is an AUR package, in which case you should be seeing an update or you just need to rebuild the package from the AUR yourself.

**Comment by loathingKernel** [comment]
Just took a look in the ArcoLinux repositories (which are hosted as a git repository, a huge facepalm in its own way), and the version they are hosting is `1.9.5`. Due to the age of that version, it is most likely built against `python 3.10` and that is why it is failing for you, since your system has been updated to `python 3.11` from the error log you have provided. You either need to rebuild it from AUR or file a bug report to the ArcoLinux people. This is not a problem with Rare.

**Comment by loathingKernel** [comment]
Closing as packaging issue.
