### ISSUE TITLE
Arch/Manjaro Error

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#5]
I managed to install Rare-0.2, but with minimal issues I got it to login, but after that it won't get anywhere after logging in, provided some error info.. I Love the idea of a Gui for Legendary..

python setup.py install --user (How I installed it..)

[Load Error After Login]
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
  File "/home/angel/.local/bin/rare", line 33, in <module>
    sys.exit(load_entry_point('Rare==0.1', 'console_scripts', 'rare')())
  File "/home/angel/.local/lib/python3.9/site-packages/Rare-0.1-py3.9.egg/Rare/Main.py", line 38, in main
  File "/home/angel/.local/lib/python3.9/site-packages/Rare-0.1-py3.9.egg/Rare/MainWindow.py", line 12, in __init__
  File "/home/angel/.local/lib/python3.9/site-packages/Rare-0.1-py3.9.egg/Rare/MainWindow.py", line 33, in __init__
  File "/home/angel/.local/lib/python3.9/site-packages/Rare-0.1-py3.9.egg/Rare/TabWidgets.py", line 45, in __init__
KeyError: 'Rare'
Release of profile requested but WebEnginePage still not deleted. Expect troubles !

**Comment by Dummerle** [comment]
The releases are not up to date. You can clone the repository and install it. Or you use the aur package

**Comment by Angell1993** [comment]
I downloaded v0.1.1 then it worked so far..
