### ISSUE TITLE
Pipe Not Found - Is Discord Running

### ISSUE THREAD

**Issue by cathaysia** [Dummerle/Rare#55]
**Describe the bug**

terminated after start rare

**To Reproduce**
1. install rare
2. enter rare in cmd

**System information (please complete the following information):**
 - win10
 - Python 3.9.1

**Additional context**

here are some logs:

```
C:\Windows\system32>rare
qt.qpa.fonts: Unable to enumerate family ' "Noto Sans Inscriptional Parthian" '
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\site-packages\pypresence\baseclient.py", line 134, in handshake
    self.sock_writer, _ = await self.loop.create_pipe_connection(lambda: reader_protocol, self.ipc_path)
  File "c:\programdata\miniconda3\lib\asyncio\windows_events.py", line 333, in create_pipe_connection
    pipe = await f
  File "c:\programdata\miniconda3\lib\asyncio\windows_events.py", line 652, in connect_pipe
    handle = _overlapped.ConnectPipe(address)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
# read: FileNotFoundError: [WinError 2] system can't find needed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\site-packages\rare\app.py", line 82, in start_app
    self.mainwindow = MainWindow(self.core, self.args)
  File "c:\programdata\miniconda3\lib\site-packages\rare\components\main_window.py", line 31, in __init__
    self.rpc = DiscordRPC(core)
  File "c:\programdata\miniconda3\lib\site-packages\rare\utils\rpc.py", line 24, in __init__
    self.set_discord_rpc()
  File "c:\programdata\miniconda3\lib\site-packages\rare\utils\rpc.py", line 58, in set_discord_rpc
    self.RPC.connect()
  File "c:\programdata\miniconda3\lib\site-packages\pypresence\presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "c:\programdata\miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\programdata\miniconda3\lib\site-packages\pypresence\baseclient.py", line 136, in handshake
    raise InvalidPipe
pypresence.exceptions.InvalidPipe: Pipe Not Found - Is Discord Running?
```

**Comment by Dummerle** [comment]
I pushed a new commit, which should fix this error. If you run it from source, it should be fixed

**Comment by cathaysia** [comment]
> 
> 
> I pushed a new commit, which should fix this error. If you run it from source, it should be fixed

this bug exists still after I run it from source.
The setups as follow:

```cmd
git clone git@github.com:Dummerle/Rare.git --depth 1
cd rare
python3 rare
```

The exceptions occur:

```cmd
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pypresence\baseclient.py", line 134, in handshake
    self.sock_writer, _ = await self.loop.create_pipe_connection(lambda: reader_protocol, self.ipc_path)
  File "C:\ProgramData\Miniconda3\lib\asyncio\windows_events.py", line 333, in create_pipe_connection
    pipe = await f
  File "C:\ProgramData\Miniconda3\lib\asyncio\windows_events.py", line 652, in connect_pipe
    handle = _overlapped.ConnectPipe(address)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Drago\AppData\Roaming\Python\Python39\site-packages\rare\app.py", line 82, in start_app
    self.mainwindow = MainWindow(self.core, self.args)
  File "C:\Users\Drago\AppData\Roaming\Python\Python39\site-packages\rare\components\main_window.py", line 32, in __init__
    self.rpc = DiscordRPC(core)
  File "C:\Users\Drago\AppData\Roaming\Python\Python39\site-packages\rare\utils\rpc.py", line 24, in __init__
    self.set_discord_rpc()
  File "C:\Users\Drago\AppData\Roaming\Python\Python39\site-packages\rare\utils\rpc.py", line 58, in set_discord_rpc
    self.RPC.connect()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pypresence\presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "C:\ProgramData\Miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pypresence\baseclient.py", line 136, in handshake
    raise InvalidPipe
pypresence.exceptions.InvalidPipe: Pipe Not Found - Is Discord Running?
```

If I use ``python rare --offline``, it works.

**Comment by cathaysia** [comment]
> 
> 
> I pushed a new commit, which should fix this error. If you run it from source, it should be fixed

Yes, It works now. :) Thanks for your work!
