### ISSUE TITLE
Rare does not start anymore ?

### ISSUE THREAD

**Issue by Trokinos** [Dummerle/Rare#77]
Hello, was using Rare 1.3.1 on window 10, as the Rare.exe didn't work at all for downloads, i followed some advice and after installing latest python (3.9.something) i did in command prompt :  
`pip install Rare `
So far so good, as when using the command prompt and typing :
`Rare`

It worked, as it launched Rare and the downloads actually worked.  
Today after download Epic last freebie , "Control" and playing with it for a bit and not really appreciating it , i decided to just uninstall it as it was taking quite a lot of gb that i had no use of.  
So i typed 
`Rare`
 in command prompt, the "loading image" screen appeared but the bar didn't progressed anymore.
After a while there's some error message in the command prompt window.  
Decided to uninstall both
`pip uninstall Rare` 
and uninstall Python 3.9.something , and delete the directory left behind.  
All to make sure i was starting again without possibly broken configuration. 
Installed Python, then 
`pip install Rare`  
Only to notice this time it install the version 1.4.1 , and after installation, it does not launch.
After noticing : 
https://github.com/Dummerle/Rare/issues/59
i then did a 
`pip install pywin32`

And it solved the issue, Rare started to launch (the downloading image thing again) , but sadly it again stopped there, same error message as before :

>Traceback (most recent call last):
  File "c:\python\python39\lib\site-packages\rare\components\dialogs\launch_dialog.py", line 25, in run
    download_images(self.download_progess, self.core)
  File "c:\python\python39\lib\site-packages\rare\utils\utils.py", line 31, in download_images
    games, dlcs = core.get_game_and_dlc_list()
  File "c:\python\python39\lib\site-packages\custom_legendary\core.py", line 230, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "c:\python\python39\lib\site-packages\custom_legendary\core.py", line 200, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "c:\python\python39\lib\site-packages\custom_legendary\api\egs.py", line 102, in get_game_assets
    r.raise_for_status()
  File "c:\python\python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live

I have no idea what most of this error means, but in the end it looks like there's a server that is not responding, is it the image download thingy ? 
Maybe there should be a way for Rare to ignore non-responding image server so you can uninstall things or edit options in Rare.
(Legendary still works without problem as i can launch games with it)

**Comment by ChemicalXandco** [comment]
Epic is currently having issues, see: https://github.com/derrod/legendary/issues/284

**Comment by Trokinos** [comment]
Thanks for the report, still i think the user should be able to get to Rare main menu and various options regardless of Epic being down or up.

**Comment by Dummerle** [comment]
There is already an offline mode. It starts, if rare fails to login or if you launch rare with --offline option. Maybe I should add it for other errors

**Comment by Trokinos** [comment]
I wasn't aware of Rare having an --offline argument, i thought it was only Legendary for launching game offline.
I just tested it and it does not seem to work , it produce the same error when the epic server is down :

>Rare --offline
Traceback (most recent call last):
  File "c:\python\python39\lib\site-packages\rare\app.py", line 81, in start_app
    self.mainwindow = MainWindow(self.core, self.args)
  File "c:\python\python39\lib\site-packages\rare\components\main_window.py", line 30, in __init__
    self.tab_widget = TabWidget(core, self, args.offline)
  File "c:\python\python39\lib\site-packages\rare\components\tab_widget.py", line 29, in __init__
    self.games_tab = GameTab(core, self, offline)
  File "c:\python\python39\lib\site-packages\rare\components\tabs\games\__init__.py", line 16, in __init__
    self.default_widget = Games(core, self, offline)
  File "c:\python\python39\lib\site-packages\rare\components\tabs\games\__init__.py", line 52, in __init__
    self.game_list = GameList(core, self, offline)
  File "c:\python\python39\lib\site-packages\rare\components\tabs\games\game_list.py", line 41, in __init__
    self.init_ui(icon_view)
  File "c:\python\python39\lib\site-packages\rare\components\tabs\games\game_list.py", line 70, in init_ui
    self.bit32 = [i.app_name for i in self.core.get_game_and_dlc_list(True, "Win32")[0]]
  File "c:\python\python39\lib\site-packages\custom_legendary\core.py", line 230, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "c:\python\python39\lib\site-packages\custom_legendary\core.py", line 194, in get_assets
    self.egs.get_game_assets(platform=platform_override)]
  File "c:\python\python39\lib\site-packages\custom_legendary\api\egs.py", line 102, in get_game_assets
    r.raise_for_status()
  File "c:\python\python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Win32?label=Live

**Comment by Dummerle** [comment]
I pushed a commit, which should fix offline mode

**Comment by Trokinos** [comment]
Thank you !
